'use client';

import Millis from '@millisai/web-sdk';
import { useState, useEffect, useRef } from 'react';

// Define a proper type for the Millis client
type MillisClient = ReturnType<typeof Millis.createClient>;

interface VoiceAgentProps {
  language?: string;
}

export default function VoiceAgent({ language = 'english' }: VoiceAgentProps) {
  const [isListening, setIsListening] = useState(false);
  const [messages, setMessages] = useState<Array<{type: 'user' | 'agent', text: string}>>([]);
  const [currentAgentResponse, setCurrentAgentResponse] = useState<string | null>(null);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const msClientRef = useRef<MillisClient | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const typingMessageRef = useRef<HTMLDivElement>(null);
  const [permissionGranted, setPermissionGranted] = useState(false);
  const [connectionError, setConnectionError] = useState<string | null>(null);

  useEffect(() => {
    // Initialize the client only once
    if (!msClientRef.current) {
      const publicKey = process.env.NEXT_PUBLIC_MILLIS_PUBLIC_KEY || 'F0DzXOcj6UDsfULztsNQuS4HBXDJntNg';
      msClientRef.current = Millis.createClient({
        publicKey: publicKey,
        endPoint: 'wss://api-eu-west.millis.ai/millis'
      });
      
      setupEventListeners();
    }
    checkMicrophonePermission();

    return () => {
      if (msClientRef.current && isListening) {
        msClientRef.current.stop();
      }
    };
  }, [isListening]);

  useEffect(() => {
    scrollToBottom();
    //eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages]);

  // Add a new effect to scroll when the current agent response updates
  useEffect(() => {
    if (currentAgentResponse) {
      scrollToBottom();
    }
    //eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentAgentResponse]);

  const checkMicrophonePermission = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      setPermissionGranted(true);
  
      const tracks = stream.getTracks();
      tracks.forEach(track => track.stop());
    } catch (err) {
      console.error('Error accessing microphone:', err);
      setConnectionError('Microphone access is required for the voice agent to work.');
      setPermissionGranted(false);
    }
  };

  const setupEventListeners = () => {
    if (!msClientRef.current) return;
    
    const msClient = msClientRef.current;

    msClient.on("onopen", () => {
      console.log("Connected to Millis AI server");
      setConnectionError(null);
    });

    msClient.on("onready", () => {
      console.log("Voice agent is ready");
    });

    msClient.on("onaudio", () => {
      // The agent is speaking - this event is triggered when audio is playing
      setIsSpeaking(true);
    });

    msClient.on("onresponsetext", (text: string, payload: { is_final?: boolean }) => {
      console.log("Response text:", text, payload);
      
      // When we get any text update, show the text immediately as it's being spoken
      // This way the text appears in real-time with the speech
      setCurrentAgentResponse(text);
      
      // Only when the response is final, add it to the messages array
      if (payload.is_final) {
        // The agent has finished speaking
        setIsSpeaking(false);
        
        // Add a slight delay to allow users to see the completed text before
        // it gets added to the message history
        setTimeout(() => {
          const agentMessage = { type: 'agent' as const, text };
          setMessages(prev => [...prev, agentMessage]);
          setCurrentAgentResponse(null);
        }, 500);
      }
    });

    msClient.on("onspeechend", () => {
      console.log("Agent speech ended");
      setIsSpeaking(false);
    });

    msClient.on("ontranscript", (text: string, payload: { is_final?: boolean }) => {
      console.log("Transcript:", text, payload);
      if (payload.is_final && text) {
        const userMessage = { type: 'user' as const, text };
        setMessages(prev => [...prev, userMessage]);
      }
    });

    msClient.on("useraudioready", (data: { analyser: AnalyserNode; stream: MediaStream }) => {
      console.log("User audio is ready", data);
    });

    msClient.on("onsessionended", () => {
      console.log("Session ended");
      setIsListening(false);
    });

    msClient.on("onclose", (event: CloseEvent) => {
      console.log("Connection closed", event);
      setIsListening(false);
      
      // Only show errors for unexpected closures
      // 1000: Normal closure
      // 1001: Going away (page close/reload)
      // 1005: No status code present
      // 1006: Abnormal closure (handled differently in browsers)
      // 1011: Server terminating connection
      // 1005 and 1006 are generated by browsers, not sent over the wire
      const expectedClosureCodes = [1000, 1001, 1005];
      if (!expectedClosureCodes.includes(event.code)) {
        setConnectionError(`Connection closed unexpectedly (code: ${event.code}). Reason: ${event.reason || 'Unknown'}`);
      } else {
        // Clear any existing connection error for expected closures
        setConnectionError(null);
      }
    });

    msClient.on("onerror", (error: Event) => {
      console.error("Error occurred:", error);
      setIsListening(false);
      setConnectionError("An error occurred with the voice connection. Please try again.");
    });
  };

  const scrollToBottom = () => {
    // Use setTimeout to ensure this happens after the DOM has been updated
    setTimeout(() => {
      // If there's a typing message, scroll to that
      if (currentAgentResponse && typingMessageRef.current) {
        typingMessageRef.current.scrollIntoView({ 
          behavior: 'smooth',
          block: 'end'
        });
      } else if (messagesEndRef.current) {
        // Otherwise scroll to the end of messages
        messagesEndRef.current.scrollIntoView({ 
          behavior: 'smooth',
          block: 'end'
        });
      }
    }, 10);
  };

  const startVoiceAgent = async () => {
    if (!permissionGranted) {
      await checkMicrophonePermission();
      if (!permissionGranted) return;
    }
    
    if (!msClientRef.current) {
      setConnectionError("Client initialization failed. Please refresh the page.");
      return;
    }
    
    setConnectionError(null);
    
    try {
      // Create a complete configuration using all environment variables
      const apiKey = process.env.NEXT_PUBLIC_MILLIS_API_KEY;
      
      // Select the appropriate agent ID based on the language
      const agentId = language === 'romanian' 
        ? process.env.NEXT_PUBLIC_MILLIS_ROMANIAN_AGENT_ID
        : process.env.NEXT_PUBLIC_MILLIS_ENGLISH_AGENT_ID || process.env.NEXT_PUBLIC_MILLIS_AGENT_ID;
      
      msClientRef.current.start({
        agent: {
          agent_id: agentId,
        },
        metadata: {
          apiKey: apiKey,
          useOpenAIProxy: process.env.NEXT_PUBLIC_USE_OPENAI_PROXY === 'true',
          language: language
        },
        include_metadata_in_prompt: true
      });
      
      setIsListening(true);
    } catch (err) {
      console.error("Error starting voice agent:", err);
      setConnectionError("Failed to start the voice agent. Please try again.");
    }
  };

  const stopVoiceAgent = () => {
    if (msClientRef.current) {
      msClientRef.current.stop();
    }
    setIsListening(false);
    // Clear any connection error when the user deliberately stops the agent
    setConnectionError(null);
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4">
      <div className="w-full max-w-2xl bg-white rounded-lg shadow-xl p-6">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center">
            <h1 className="text-2xl font-bold text-gray-800">Cloud Companion</h1>
          </div>
          <div className="flex items-center">
            {isListening && <div className="w-3 h-3 bg-red-500 rounded-full mr-2 animate-pulse"></div>}
            <span className="text-sm text-gray-500">
              {isSpeaking ? 'Speaking...' : isListening ? 'Listening...' : 'Not active'}
            </span>
          </div>
        </div>

        {connectionError && (
          <div className="mb-4 p-3 bg-red-100 text-red-700 rounded-lg">
            {connectionError}
          </div>
        )}

        <div className="space-y-4 mb-6 h-96 overflow-y-auto p-4 bg-gray-50 rounded-lg">
          {messages.map((msg, idx) => (
            <div key={idx} className={`p-3 rounded-lg ${msg.type === 'user' ? 'bg-blue-100 ml-auto max-w-[80%]' : 'bg-gray-200 mr-auto max-w-[80%]'}`}>
              <p className="text-gray-800">{msg.text}</p>
            </div>
          ))}
          
          {/* Show the current response being typed */}
          {currentAgentResponse && (
            <div ref={typingMessageRef} className="p-3 rounded-lg bg-gray-200 mr-auto max-w-[80%]">
              <p className="text-gray-800">
                {currentAgentResponse}
                {isSpeaking && <span className="animate-pulse">|</span>}
              </p>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>

        <div className="flex items-center justify-center">
          <button
            onClick={isListening ? stopVoiceAgent : startVoiceAgent}
            className={`w-full py-3 rounded-lg ${isListening 
              ? 'bg-red-500 hover:bg-red-600' 
              : 'bg-green-500 hover:bg-green-600'} 
              text-white font-medium transition-colors`}
          >
            {isListening ? 'Stop Listening' : 'Start Voice Agent'}
          </button>
        </div>
      </div>
    </div>
  );
} 